#ifndef _BOUNDS_H_
#define _BOUNDS_H_  1

/*
 * DO NOT MODIFY
 *
 * This file was generated by Kbuild
 */

#define NR_PAGEFLAGS 22

/* Support DMA32 */
#ifdef CONFIG_DMA32
/* Support DMA */
#ifdef CONFIG_DMA
/* Support HIGHMEM */
#ifdef CONFIG_HIGHMEM
#define MAX_NR_ZONES 5
#else
/* Not support HIGHMEM */
#define MAX_NR_ZONES 4
#endif

/* Not support DMA */
#else
/* Support HIGHMEM */
#ifdef CONFIG_HIGHMEM
#define MAX_NR_ZONES 4
/* Not support HIGHMEM */
#else
#define MAX_NR_ZONES 3
#endif
#endif

/* Not support DMA32 */
#else
/* Support DMA */
#ifdef CONFIG_DMA
/* Support HIGMEM */
#ifdef CONFIG_HIGHMEM
#define MAX_NR_ZONES 4
/* Not support HIGHMEM */
#else
#define MAX_NR_ZONES 3
#endif
/* Not support DMA */
#else
/* Support HIGHMEM */
#ifdef CONFIG_HIGHMEM
#define MAX_NR_ZONES 3
/* Not support HIGHMEM */
#else
#define MAX_NR_ZONES 2
#endif
#endif
#endif








//#define MAX_NR_ZONES 2

#endif
