#ifndef _BOUNDS_H_
#define _BOUNDS_H_  1

/*
 * DO NOT MODIFY
 *
 * This file was generated by Kbuild
 */

#define NR_PAGEFLAGS 22 
#ifndef CONFIG_HIGHMEM
#define MAX_NR_ZONES 2
#else
#define MAX_NR_ZONES 3
#endif

#endif
