CURRENT_SOURCE := init.c
CURRENT_SOURCE += ctype.c
CURRENT_SOURCE += atags.c
CURRENT_SOURCE += cmdline.c
CURRENT_SOURCE += compat.c
CURRENT_SOURCE += cpuset.c
CURRENT_SOURCE += do_mounts.c
CURRENT_SOURCE += head.c
CURRENT_SOURCE += hexdump.c
CURRENT_SOURCE += init_task.c
CURRENT_SOURCE += mach-6410.c
CURRENT_SOURCE += params.c
CURRENT_SOURCE += reboot.c
CURRENT_SOURCE += resource.c
CURRENT_SOURCE += setup.c
CURRENT_SOURCE += sort.c
CURRENT_SOURCE += string.c
CURRENT_SOURCE += vsprintf.c
CURRENT_SOURCE += wait.c

all:
	@cp ${CURRENT_SOURCE} ${OBJS_PATH}
OBJS_PATH = ../../${OBJS_DIR}
