CURRENT_SOURCE := sort.c
CURRENT_SOURCE += cmdline.c
CURRENT_SOURCE += ctype.c
CURRENT_SOURCE += hexdump.c
CURRENT_SOURCE += string.c
CURRENT_SOURCE += vsprintf.c
CURRENT_SOURCE += radix-tree.c
CURRENT_SOURCE += rbtree.c



OBJS_PATH = ../${OBJS_DIR}
all:    
	@cp ${CURRENT_SOURCE} ${OBJS_PATH} 
