CURRENT_SOURCE := memblock.c
CURRENT_SOURCE += bootmem.c
CURRENT_SOURCE += page_alloc.c
CURRENT_SOURCE += debug-pagealloc.c
CURRENT_SOURCE += highmem.c
CURRENT_SOURCE += init-mm.c
CURRENT_SOURCE += kmemcheck.c
CURRENT_SOURCE += memcontrol.c
CURRENT_SOURCE += memory.c
CURRENT_SOURCE += mm_init.c
CURRENT_SOURCE += mmzone.c
CURRENT_SOURCE += page_cgroup.c
CURRENT_SOURCE += percpu.c
CURRENT_SOURCE += percpu-km.c
CURRENT_SOURCE += pte.c
CURRENT_SOURCE += slub.c
CURRENT_SOURCE += swap.c
CURRENT_SOURCE += swap_state.c
CURRENT_SOURCE += vmalloc.c
CURRENT_SOURCE += vmscan.c
CURRENT_SOURCE += vmstat.c
CURRENT_SOURCE += util.c

all:
	@cp ${CURRENT_SOURCE} ${OBJS_PATH}
OBJS_PATH = ../${OBJS_DIR}
