CURRENT_SOURCE := setup.c
CURRENT_SOURCE += atags.c
CURRENT_SOURCE += compat.c
CURRENT_SOURCE += init_task.c
CURRENT_SOURCE += reboot.c
CURRENT_SOURCE += traps.c

all:
	@cp ${CURRENT_SOURCE} ${OBJS_PATH}
OBJS_PATH = ../../../${OBJS_DIR}
