CURRENT_SOURCE := boot_arch.c
CURRENT_SOURCE += debug.c
CURRENT_SOURCE += register_simulate.c
CURRENT_SOURCE += TestCase_slub.c
CURRENT_SOURCE += TestCase_buddy.c
CURRENT_SOURCE += TestCase_Per_Cpu_Page.c
CURRENT_SOURCE += TestCase_vmalloc.c
CURRENT_SOURCE += TestCase_RB_tree.c
CURRENT_SOURCE += TestCase_kmap.c
CURRENT_SOURCE += TestCase_Hash.c
CURRENT_SOURCE += TestCase_waitqueue.c
CURRENT_SOURCE += TestCase_radix_tree.c

all:
	@cp ${CURRENT_SOURCE} ${OBJS_PATH}
OBJS_PATH = ../${OBJS_DIR}
